version: '2'
services:
  web-pozos-jean:
    images: php:apache
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=jean
      - PASSWORD=agree
    networks:
      - api-pozos-jean

  api-pozos-jean:
    image: api-pozos-jean:1
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api-pozos-jean

networks:
  api-pozos-jean:  