services:
  service-simple-api-jean:
    image: simple-api-jean:latest
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - simple-api-network

  service-php-apache-jean:
    image: php-apache-jean:latest
    depends_on:
      - service-simple-api-jean
    ports:
      - "8082:80"
    volumes:
      - ./website/www:/var/www/html
    environment:
      USERNAME: jean
      PASSWORD: agree
    networks:
      - simple-api-network

networks:
  simple-api-network:
    driver: bridge