services:
  service-simple-api-jean:
    image: simple-api-jean:latest
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - simple-api-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/simple-jean/api/v1.0/get_student_ages"]
      interval: 10s
      retries: 5
      start_period: 20s

  service-php-apache-jean:
    image: php-api-jean:latest
    depends_on:
      service-simple-api-jean:
        condition: service_healthy
    ports:
      - "8082:80"
    volumes:
      - ./website/www:/var/www/html
    environment:
      USERNAME: jean
      PASSWORD: agree
    networks:
      - simple-api-network

networks:
  simple-api-network:
    driver: bridge

