version: '2'
services:
  web-simple-api-jean:
    images: php:apache
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=jean
      - PASSWORD=agree
    networks:
      - simple-api-jean-networks

  simple-api-jean:
    image: simple-api-jean:latest
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - simple-api-jean-networks

networks:
  simple-api-jean-networks: