version: '3.8'  # Utilisation d'une version plus récente

services:
  simple-api-jean:
    image: simple-api-jean:latest
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - simple-api-network
    healthcheck:  # Vérifie que l'API Flask est bien démarrée
      test: ["CMD", "curl", "-f", "http://localhost:4000/simple-jean/api/v1.0/get_student_ages"]
      interval: 10s
      retries: 5
      start_period: 20s
  web-php-apache-jean:
    image: php-apache-jean:latest
    depends_on:
      simple-api-jean:
        condition: service_healthy  # Assure que l'API est prête avant de démarrer
    ports:
      - "8082:80"
    volumes:
      - ./website/www:/var/www/html  # Monte tout le dossier au lieu d'un seul fichier
    environment:
      USERNAME: jean
      PASSWORD: agree
    networks:
      - simple-api-network

networks:
  simple-api-network:
    driver: bridge 
